// leave off @2x/@3x
const images = {
  profile: {
    arrow: require('../Images/profile/arrow.png'),
  },
  booking: require('../Images/booking.png'),
  skip: require('../Images/Skip.png'),
  splash: require('../Images/splash.png'),
  onboarding: {
    first: require('../Images/onboarding/onBoarding1.png'),
    secondImg: require('../Images/onboarding/onBoarding2.png'),
    third: require('../Images/onboarding/onBoarding3.png'),
    skip: require('../Images/onboarding/skip.png'),
  },
  map: {
    pin_green: require('../Images/map/pin_gre.png'),
    pin_yellow: require('../Images/map/pin_yel.png'),
    pin_red: require('../Images/map/pin_red.png'),
  },
  beach: {
    placeholder: require('../Images/beach/placeholder.png'),
    sand: require('../Images/beach/sand.png'),
    cliff: require('../Images/beach/cliff.png'),
    parking: require('../Images/beach/parking.png'),
    disabled: require('../Images/beach/disabled.png'),
    dogs: require('../Images/beach/dogs.png'),
    noBathing: require('../Images/beach/noBathing.png'),
    blueFlag: require('../Images/beach/blueFlag.png'),
    book: require('../Images/beach/book.png'),
    openings: require('../Images/beach/openings.png'),
    state: {
      1: require('../Images/beachSpotState/empty.png'),
      2: require('../Images/beachSpotState/normal.png'),
      3: require('../Images/beachSpotState/full.png'),
    }
  },
  description: {
    desc1: require('../Images/Description/spiagge-bimbi.png'),
    desc2: require('../Images/Description/spiagge-bimbi2.png'),
  },
  macros: {
    family: require('../Images/Macros/family.png'),
    nature: require('../Images/Macros/nature.png'),
    sport: require('../Images/Macros/sport.png'),
  },
  weather: {
    wind: require('../Images/weather/wind.png'),
    sun: require('../Images/weather/sun.png'),
    cloudMid: require('../Images/weather/cloud-mid.png'),
    cloudFull: require('../Images/weather/cloud-full.png'),
    rainMid: require('../Images/weather/rain-mid.png'),
    rainFull: require('../Images/weather/rain-full.png'),
    sea: require('../Images/weather/sea.png'),
    seaMid: require('../Images/weather/sea-mid.png'),
    seaFull: require('../Images/weather/sea-full.png'),
  },
  report: {
    boys: require('../Images/report/boys.png'),
    light: require('../Images/report/redLight.png'),
    tree: require('../Images/report/tree.png'),
  },
  emptyRes: require('../Images/emptyRes.png'),
  sdraio: require('../Images/emptyFav.png'),
  emptyHis: require('../Images/emptyResHis.png'),

  weAreInPuglia: require('../Images/weareinpuglia.png'),
  bg: require('../Images/Background.jpg'),
  logo: require('../Images/Logo.png'),
  ticketCover: require('../Images/ticket-cover.png'),
  beachBG: require('../Images/beach.png'),
  user: require('../Images/user.png'),
  calendar: require('../Images/Summary/Calender.png'),
  tag: require('../Images/Summary/Tag.png'),
  // logo: {
  //   oreegano: require("../Images/oreegano_homelogo.png"),
  //   candy: require("../Images/haier/LogoCandy_ok.png"),
  //   hoover: require("../Images/haier/LogoHoover_ok.png"),
  //   candy_noborders: require("../Images/haier/Candy-noborders.png"),
  // },
  // login_page: {
  //   logo_undefined: require("../Images/login_page/logo-undefined.png"),
  //   logo_mia: require("../Images/login_page/logo-mia.png"),
  //   logo_personal_recipebook: require("../Images/login_page/logo-personal-recipebook.png"),
  //   logo_shopping_list: require("../Images/login_page/logo-shopping.png"),
  //   logo_profile: require("../Images/login_page/logo-profile.png"),
  //   background_undefined: require("../Images/login_page/background-profile.jpg"),
  //   background_mia: require("../Images/login_page/background-mia.jpg"),
  //   background_personal_recipebook: require("../Images/login_page/background-personal-recipebook.jpg"),
  //   background_shopping_list: require("../Images/login_page/background-shopping.jpg"),
  //   background_profile: require("../Images/login_page/background-profile.jpg"),
  // },
  // oven_cooking_type: require("../Images/oven_cooking_type.png"),
  // oven_cooking_timer: require("../Images/oven_cooking_timer.png"),
  // oven_cooking_temp: require("../Images/oven_cooking_temp.png"),
  // headerlogo: require("../Images/headerlogo.png"),
  // userloadpic: require("../Images/avatar.png"),
  // favGreen: require("../Images/favGreen.png"),
  // favRed: require("../Images/favRed.png"),
  // staticCover: "https://res.cloudinary.com/oreegano/image/upload/q_auto/v1/static/",
  // cake: require("../Images/cookie_cut.jpg"),
  // tortellini: require("../Images/tortellini_cut.jpg"),
  // zucchine: require("../Images/zucchine_cut.jpg"),
  // sub: require("../Images/sub_cut.jpg"),
  // miaBG: require("../Images/mia_cut.jpg"),
  // swipeLeft: require("../Images/swipeleft.png"),
  // swipeRight: require("../Images/swiperight.png"),
  // splashScreen: require("../Images/oreegano_spash.png"),
  // translate: require("../Images/translate.png"),
  // translate2: require("../Images/translate2.png"),
  // error: require("../Images/error_icon.png"),
  // shopping: require("../Images/rcp_detail.png"),
  // placeholder: require("../Images/placeholder.png"),
  // avocado: require("../Images/avocado.gif"),
  // avocado1: require("../Images/avocado1.gif"),
  // avocado2: require("../Images/avocado2.gif"),
  // avocado3: require("../Images/avocado3.gif"),
  // avocado4: require("../Images/avocado4.gif"),
  // cake2: require("../Images/cake.gif"),
  // doughnut: require("../Images/doughnut.gif"),
  // juice: require("../Images/juice.gif"),
  // salad: require("../Images/salad.gif"),
  // salad2: require("../Images/salad2.gif"),
  // phOnion: require("../Images/placeholders_error.png"),
  // phBook: require("../Images/placeholders_rcpnotavailable.png"),
  // phAvocado: require("../Images/placeholders_norcps.png"),
  // phLost: require("../Images/placeholders_usrnotfound.png"),
  // avTab: require("../Images/AVbutton.png"),
  // avTab2: require("../Images/AVbutton2.png"),
  // avTab3: require("../Images/AVbutton3.png"),
  // av: {
  //   diary: require("../Images/av/av_diary.png"),
  //   mic: require("../Images/av/av_mic.png"),
  // },
  // avBg: require("../Images/AVbg.png"),
  // avMia: require("../Images/mia_button.png"),
  // calocount: require("../Images/calocount_icon.png"),
  // inspire: require("../Images/inspire_icon.png"),
  // lifestyle: require("../Images/lifestyle_icon.png"),
  // save: require("../Images/saverecipe_icon.png"),
  // ingredientCategories: {
  //   nocategory: require("../Images/ingredient_categories/no_categ.png"),
  //   alghe: require("../Images/ingredient_categories/alghe.png"),
  //   bevandeAnalcoliche: require("../Images/ingredient_categories/bevande.png"),
  //   bevandeAlcoliche: require("../Images/ingredient_categories/bevande_alcoli.png"),
  //   carneBianca: require("../Images/ingredient_categories/carne_bianca.png"),
  //   carneRossa: require("../Images/ingredient_categories/carne_rossa.png"),
  //   cereali: require("../Images/ingredient_categories/cereali.png"),
  //   cremeConserve: require("../Images/ingredient_categories/creme_conserve.png"),
  //   dolci: require("../Images/ingredient_categories/dolci.png"),
  //   erbeSpezie: require("../Images/ingredient_categories/erbe_spezie.png"),
  //   frutta: require("../Images/ingredient_categories/frutta.png"),
  //   grassiOlii: require("../Images/ingredient_categories/grassi_olii.png"),
  //   integratori: require("../Images/ingredient_categories/integratori.png"),
  //   latticini: require("../Images/ingredient_categories/latticini.png"),
  //   latte: require("../Images/ingredient_categories/latte.png"),
  //   legumiFreschi: require("../Images/ingredient_categories/legumi_freschi.png"),
  //   legumiSecchi: require("../Images/ingredient_categories/legumi_secchi.png"),
  //   prodottiDaForno: require("../Images/ingredient_categories/prodotti_da_forno.png"),
  //   pesce: require("../Images/ingredient_categories/pesce.png"),
  //   salseSughi: require("../Images/ingredient_categories/salse_sughi.png"),
  //   semiNoci: require("../Images/ingredient_categories/semi_noci.png"),
  //   uova: require("../Images/ingredient_categories/uova.png"),
  //   verdure: require("../Images/ingredient_categories/verdure.png"),
  //   molluschi: require("../Images/ingredient_categories/molluschi.png"),
  //   tuberi: require("../Images/ingredient_categories/tuberi.png"),
  //   derivatiVegetali: require("../Images/ingredient_categories/derivati_veg.png"),
  //   affettati: require("../Images/ingredient_categories/affettati.png"),
  //   affettatiVegetali: require("../Images/ingredient_categories/affettati_veg.png"),
  //   addensanti: require("../Images/ingredient_categories/addensanti.png"),
  //   crostacei: require("../Images/ingredient_categories/crostacei.png"),
  //   pasta: require("../Images/ingredient_categories/pasta.png"),
  //   piattiPronti: require("../Images/ingredient_categories/piattipronti2.png"),
  // },
  // activities: {
  //   axe: require('../Images/activities/axe.png'),
  //   casco: require('../Images/activities/casco.png'),
  //   dance: require('../Images/activities/dance.png'),
  //   fly: require('../Images/activities/fly.png'),
  //   sub: require('../Images/activities/sub.png'),
  //   corsa: require('../Images/activities/corsa.png'),
  //   bowling: require('../Images/activities/bowling.png'),
  //   pesca: require('../Images/activities/pesca.png'),
  //   boxe: require('../Images/activities/boxe.png'),
  //   combattimento: require('../Images/activities/combattimento.png'),
  //   guida: require('../Images/activities/guida.png'),
  //   baseball: require('../Images/activities/baseball.png'),
  //   basket: require('../Images/activities/basket.png'),
  //   caccia: require('../Images/activities/caccia.png'),
  //   bici: require('../Images/activities/bici.png'),
  //   biliards: require('../Images/activities/billiards.png'),
  //   calcio: require('../Images/activities/calcio.png'),
  //   camminata: require('../Images/activities/camminata.png'),
  //   canoa: require('../Images/activities/canoa.png'),
  //   equitazione: require('../Images/activities/equitazione.png'),
  //   polo: require('../Images/activities/polo.png'),
  //   acquatici: require('../Images/activities/acquatici.png'),
  //   sci: require('../Images/activities/sci.png'),
  //   bersaglio: require('../Images/activities/bersaglio.png'),
  //   forzuti: require('../Images/activities/forzuti.png'),
  //   surf: require('../Images/activities/surf.png'),
  //   sail: require('../Images/activities/sail.png'),
  //   yoga: require('../Images/activities/yoga.png'),
  //   montagna: require('../Images/activities/montagna.png'),
  //   snow: require('../Images/activities/snow.png'),
  //   tennis: require('../Images/activities/tennis.png'),
  //   gym: require('../Images/activities/gym.png'),
  //   roller: require('../Images/activities/roller.png'),
  //   pattini: require('../Images/activities/pattini.png'),
  //   pulizie: require('../Images/activities/pulizie.png'),
  //   sex: require('../Images/activities/sex.png'),
  //   volley: require('../Images/activities/volley.png'),
  //   skate: require('../Images/activities/skate.png'),
  //   golf_hockey: require('../Images/activities/golf_hockey.png'),
  //   frisbee: require('../Images/activities/frisbee.png'),
  //   slitta: require('../Images/activities/slitta.png'),
  //   sea: require('../Images/activities/sea.png'),
  //   scherma: require('../Images/activities/scherma.png'),
  //   rugby: require('../Images/activities/rugby.png'),
  //   ping_pong: require('../Images/activities/ping_pong.png'),
  //   parachute: require('../Images/activities/parachute.png'),
  //   manubrio: require('../Images/activities/manubrio.png')
  // },
  // activity: require("../Images/activity.jpg"),
  // water0: require("../Images/water/water0.png"),
  // water1: require("../Images/water/water1.png"),
  // water2: require("../Images/water/water2.png"),
  // water3: require("../Images/water/water3.png"),
  // water4: require("../Images/water/water4.png"),
  // water5: require("../Images/water/water5.png"),
  // water6: require("../Images/water/water6.png"),
  // water7: require("../Images/water/water7.png"),
  // water8: require("../Images/water/water8.png"),
  // water9: require("../Images/water/water9.png"),
  // water10: require("../Images/water/water10.png"),
  // water11: require("../Images/water/water11.png"),
  // water12: require("../Images/water/water12.png"),
  // addwater: require("../Images/addwater.png"),
  // remwater: require("../Images/remwater.png"),
  // sport: require("../Images/sport_icon.png"),
  // water: require("../Images/water_icon.png"),
  // nutri: require("../Images/nutri_icon.png"),
  // tick: require("../Images/tick.png"),
  // glassAdd: require("../Images/glass_add.png"),
  // glassFull: require("../Images/glass_full.png"),
  // glassEmpty: require("../Images/glass_empty.png"),
  // selected: require("../Images/selected.png"),
  // premium: require("../Images/premium.png"),
  // premiumBadge: require("../Images/premium_badge.png"),
  // premiumOnAcid: require("../Images/wizard.png"),
  // dieta: require("../Images/dieta_icon.png"),
  // createtip: require("../Images/onboarding/create_icon.png"),
  // recipestip: require("../Images/onboarding/recipes_icon.png"),
  // goalstip: require("../Images/onboarding/goals_icon.png"),
  // inspireOB: require("../Images/onboarding/inspire_icon.png"),
  // progressOB: require("../Images/onboarding/progress_icon.png"),
  // micOB: require("../Images/onboarding/mic_icon.png"),
  // wizardOB: require("../Images/onboarding/wizard_icon.png"),
  // lock: require("../Images/privatercp.png"),
  // av0: require("../Images/av1.jpg"),
  // av1: require("../Images/av2.jpg"),
  // av2: require("../Images/av3.jpg"),
  // av3: require("../Images/av4.jpg"),
  // arance: require("../Images/01-arance.png"),
  // crostini: require("../Images/02-crostini.png"),
  // muffin: require("../Images/03-muffin.png"),
  // bollettino: require("../Images/04-bollettino.png"),
  // check_green: require("../Images/check_green.png"),
  // check_yellow: require("../Images/check_yellow.png"),
  // check_red: require("../Images/check_yellow.png"),
  // resource_not_found: require("../Images/resource_not_found.png"),
};

export default images;
